### ISSUE TITLE
MP4 files

### ISSUE THREAD

**Issue by Christilut** [Holzhaus/serato-tags#3]
I've been building a Serato tag read/writer for my own software rekordcloud and I've based it on your code. Most file types work fine with slight modifications here and there.

But MP4/M4A files are a bit strange. For some reason Serato won't read the first 5 cue points, it always skips those. The last 3 are read properly. I've been debugging this for days and even when I'm literally writing byte identical tags, it still fails. Maybe it's how mutagen handles the FreeForm tags. Only difference I've seen in a hex editor is the tag order, but it seems strange that that would cause this.

This is what I'm doing:
```python
def dump_base64_mp4(data):
    pad_length = 1444 if len(data) > 752 else 752

    payload = b"application/octet-stream" + NULL_BYTE + NULL_BYTE + b"Serato Markers2" + NULL_BYTE + b'\x01\x01' + data

    base64payload = bytearray(base64.b64encode(payload).replace(b"=", b"A"))

    if len(base64payload) < pad_length:
        base64payload = base64payload.ljust(pad_length, b'A')
    else:
        base64payload += b'A'

    i = 72
    line_endings_added = 0
    while i < len(base64payload):
        base64payload.insert(i, 0x0A)
        i += 73
        line_endings_added += 1

    base64payload = base64payload[:len(base64payload) - line_endings_added]

    return base64payload.decode()
```

```python
def dump(entries, pad=True):
    version = struct.pack(FMT_VERSION, 0x01, 0x01)

    contents = [version]

    for entry in entries:
        if entry.NAME is None:
            contents.append(entry.dump())
        else:
            entry_data = entry.dump()
            contents.append(b"".join((entry.NAME.encode("utf-8"), NULL_BYTE, struct.pack(">I", (len(entry_data))), entry_data)))

    payload = b"".join(contents)

    payload_base64 = bytearray(base64.b64encode(payload).replace(b"=", b"A"))

    data = b''

    i = 72
    while i < len(payload_base64):
        payload_base64.insert(i, 0x0A)
        i += 73

    if pad:
        data = version

    payload_base64 += b'\x0A' # TEMP: mp4 only, not sure if its needed

    data += payload_base64

    if pad:
        if len(data) < 470:
            data = data.ljust(470, NULL_BYTE)
        else:
            data += NULL_BYTE

    return data
```

```python
new_markers2_data = serato.markers2.dump(entries_markers2, pad=False)

tags_all["----:com.serato.dj:markersv2"] = mutagen.mp4.MP4FreeForm(bytes(new_markers2_data, "utf-8"))
```

I've added the line endings and padding so that the data is really identical, but I don't think they really matter. 

I thought maybe you'd have any insights here.

**Comment by Holzhaus** [comment]
Sorry, I only focused on MP3 files so far. If you have any information regarding other file types, I'd be cool if you could open a PR to add that information as well.

**Comment by Christilut** [comment]
I've adopted the code and changed things around a bit so a PR won't work but I can do some cleanup and make a new repo for it. You can use the things I learned from there if you want.

So far I added support for FLAC, M4A, OGG and AIFF. 
AAC is a bit of a mystery (Serato seems to save, but I can't find anything in any tag) and WAV can be done soon when mutagen finishes their PR for WAV support.

**Comment by Holzhaus** [comment]
Maybe AAC is similar to MOV files? It saves the information as XML in `_Serato_/Metadata/filename.mov.xml`.

**Comment by Holzhaus** [comment]
```python
tags_all["----:com.serato.dj:markersv2"] = mutagen.mp4.MP4FreeForm(bytes(new_markers2_data, "utf-8"))
```

Why do you cast it to `bytes`? Isn't `new_markers2_data` already `bytes`? And it isn't valid UTF-8, it's raw binary, so maybe something goes wrong when trying to encode it as UTF-8?

**Comment by Christilut** [comment]
I think the [MP4FreeForm](https://mutagen.readthedocs.io/en/latest/api/mp4.html#mutagen.mp4.MP4FreeForm) expects UTF8 encoded strings.

The contents is a base64 string (this is where it's slightly different from the GEOB tags) that contains the data that Serato expects (the `application/octet-stream..Serato Markers2..` part) appended with the actual cue information encoded as base64 again.

The thing is, I compared two files (one made by Serato and one by mutagen) in a hex editor and they store the exact same thing. The only difference I can see is the order of the tags which I assume would make no difference but there's just nothing else that could be it.

**Comment by Christilut** [comment]
You're right about the AAC file, there's an XML file for it right there. Thanks for the tip!

**Comment by Christilut** [comment]
Okay took a while but figured it out (with a hint from a Serato dev):
So in the case of MP4/M4A files, the first 5 cue points and all loops are in the `Markers_` FreeForm tag but also in the `Markers2` tag with more information. They both have to exist otherwise Serato will ignore them.

In `Markers_` cues only have a color and position. It gets the name from the same cue from the `Markers2` field.

The last 3 cues are only in the `Markers2` tag.

And cues and loops that have no value still have an empty value in `Markers_`. I guess the old `Markers_` had a fixed length and when they wanted to add names to cues they didn't have enough space and they created `Markers2`. Which is probably why `Markers2` has a version number but `Markers_` doesn't.

**Comment by Holzhaus** [comment]
AFAIK `Markers_` does not have to exist. I assigned custom colors (that aren't available in Serato's color picker) to some cues in the `Markers2` tag, but it they didn't display. I removed `Markers_` completely and it works now. Maybe it's just for backwards compatibility with older Serato versions?

**Comment by Holzhaus** [comment]
By the way, if you have information about the `Markers_` tag I'd really appreciate if you could contribute them here. Just fork this repo, edit `[docs/serato_markers_.md](https://github.com/Holzhaus/serato-tags/blob/master/docs/serato_markers_.md)` and commit the changes, then open a Pull Request.

**Comment by Christilut** [comment]
That's what I thought at first too. This is only for MP4 files though, other file types don't have this. 
Try deleting all tags before writing them. If `Markers_` has empty cues/loops then it takes the data from `Markers2` and you'll see cues. But if `Markers_` doesn't exist, then it won't read the first 5 cues.

I think it's backwards compatibility that's still in there from an older version. Perhaps they removed it for MP3's and such but forgot MP4.

**Comment by Christilut** [comment]
I haven't touched `Markers_` for any other file type. That's why this took so long for me to figure out, I thought it was an old field that's not used. `Markers2` does contain everything but for some reason still requires `Markers_` for MP4.

Anyway I did write some python code for MP4 `Markers_` tags but it's very hacky code. I can contribute but I'm sure you'd rather rewrite it though.

**Comment by Holzhaus** [comment]
> This is only for MP4 files though, other file types don't have this.
> [...]
> I think it's backwards compatibility that's still in there from an older version. Perhaps they removed it for MP3's and such but forgot MP4.

Interesting, could you add this information to the MP4 section in [`docs/fileformats.md`](https://github.com/Holzhaus/serato-tags/blob/master/docs/fileformats.md)?

> Anyway I did write some python code for MP4 `Markers_` tags but it's very hacky code. I can contribute but I'm sure you'd rather rewrite it though.

Feel free to just open a PR. Even if I don't end up merging the code I can still have a look at it and use it as reference ;-)

**Comment by Christilut** [comment]
Alright I noted it in the documentation. I'll post the hacky code that I use now to create the `Markers_` data here for your reference later.

```python
EMPTY_CUE_V1 = b"\xff\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00"
EMPTY_LOOP_V1 = b"\xff\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\x00\x00\x00\x00\x03\x00"

class ColorEntry(Entry):
    # omitted the rest
    def dump_mp4_v1(self):
        return self.dump()

class CueEntry(Entry):
    def dump_mp4_v1(self):
        struct_fields = ["color", "position"]

        return b"".join((struct.pack(">I", getattr(self, "position")), b"\xff\xff\xff\xff\x00\xff\xff\xff\xff\x00", getattr(self, "color"), b"\x01\x00"))

class LoopEntry(Entry):
    def dump_mp4_v1(self):
        struct_fields = ["startposition", "endposition", "locked"]

        return b"".join((struct.pack(">I", getattr(self, "startposition")), struct.pack(">I", getattr(self, "endposition")), NULL_BYTE, b"\xff\xff\xff\xff\x00'\xaa\xe1\x03", struct.pack(">B", getattr(self, "locked"))))

def dump_mp4_v1(entries, pad=True):
    contents = b"\x02\x05\x00\x00\x00\x0e" # Don't know what this is

    for index in range(5):  # Always add cue 0 to 4, even if they don't exist
        found = False

        for entry in entries:
            if entry.NAME == "CUE" and getattr(entry, "index") == index:
                contents += entry.dump_mp4_v1()
                found = True

        if not found:
            contents += EMPTY_CUE_V1

    for index in range(8):  # Always add all loops, even if they don't exist
        found = False

        for entry in entries:
            if entry.NAME == "LOOP" and getattr(entry, "index") == index:
                contents += entry.dump_mp4_v1()
                found = True

        if not found:
            contents += EMPTY_LOOP_V1

    contents += EMPTY_LOOP_V1 # Seems to have an empty loop in between

    for entry in entries:
        if entry.NAME == "COLOR":
            contents += b"".join((NULL_BYTE, entry.dump_mp4_v1()))

    contents += NULL_BYTE

    return contents

def dump_base64_mp4_v1(data, name):
    payload = b"application/octet-stream" + NULL_BYTE + NULL_BYTE + name + NULL_BYTE + data

    base64payload = bytearray(base64.b64encode(payload).replace(b"=", b"A"))

    i = 72
    while i < len(base64payload):
        base64payload.insert(i, 0x0A)
        i += 73

    return base64payload
```

Should be useful :)

**Comment by Holzhaus** [comment]
Thanks. The format seems different from the `Markers_` format in MP3s though. I added some documentation regarding the latter. Another thing I noticed: If `Serato Markers_` not present, Serato will just use the values from `Serato Markers2` (at least when using MP3s). So you could also just delete the `Serato Markers_` tag to work around the issue.

**Comment by Christilut** [comment]
I'm doing that with MP3's yeah, just always deleting `Markers_`. But MP4's are treated differently. 
It was crucial that `Markers_` is also in use. There's also some caching in play in Serato, so restarting Serato between loading files is also necessary to see what it's really loading. 

It's a compounded issue which made it very annoying to debug.

**Comment by Holzhaus** [comment]
I had the impression that unloading a track in Seratobupdates the file time and if the file time does not change between consecutive loads, then serato will cache them. So if you unload first and then make changes they should be picked up, at least in my experience.
